name: Keep Codespaces Running

on:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes
  workflow_dispatch:  # Allow manual trigger

jobs:
  maintain_codespaces:
    runs-on: ubuntu-latest

    steps:
      - name: Install GitHub CLI and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y gh jq

      - name: Authenticate GitHub CLI with PAT Token
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_CLASSIC_TOKEN }}
        run: |
          gh auth login --with-token <<< "$GITHUB_TOKEN"

      - name: Check and Restart All Codespaces
        run: |
          CODESPACES=$(gh codespace list --json name,state | jq -c '.[]')
          echo "$CODESPACES" | while IFS= read -r codespace; do
            NAME=$(echo "$codespace" | jq -r '.name')
            STATUS=$(echo "$codespace" | jq -r '.state')
            echo "Codespace: $NAME, Status: $STATUS"
            if [ "$STATUS" == "Shutdown" ]; then
              echo "Starting $NAME..."
              gh codespace ssh -c "$NAME" --exit-on-disconnect &
            else
              echo "$NAME is already running."
            fi
          done
          wait
